DHLQa2/force-app/main/default/objects/Customer__c/fields/Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile__c</fullName>
    <label>Contact Mobile</label>
    <type>Phone</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Customer_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Comments__c</fullName>
    <label>Fc1 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Comments__c</fullName>
    <label>Fc2 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Comments__c</fullName>
    <label>Fc3 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Is_SC_Reassigned__c.field-meta.xml
<CustomField>
    <fullName>Is_SC_Reassigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is SC Reassigned</label>
    <type>Checkbox</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/NPA_Rating__c.field-meta.xml
<CustomField>
    <fullName>NPA_Rating__c</fullName>
    <label>NPA Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Reassign_Comments_1__c.field-meta.xml
<CustomField>
    <fullName>Reassign_Comments_1__c</fullName>
    <label>Reassign Comments 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Reassign_Comments_2__c.field-meta.xml
<CustomField>
    <fullName>Reassign_Comments_2__c</fullName>
    <label>Reassign Comments 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Reassign_Comments_3__c.field-meta.xml
<CustomField>
    <fullName>Reassign_Comments_3__c</fullName>
    <label>Reassign Comments 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Reassign_Comments_4__c.field-meta.xml
<CustomField>
    <fullName>Reassign_Comments_4__c</fullName>
    <label>Reassign Comments 4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Reassign_Comments_5__c.field-meta.xml
<CustomField>
    <fullName>Reassign_Comments_5__c</fullName>
    <label>Reassign Comments 5</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc1_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc1_Callback_Date__c</fullName>
    <label>Rsc1 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Rsc1_Comments__c</fullName>
    <label>Rsc1 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc1_Status__c.field-meta.xml
<CustomField>
    <fullName>Rsc1_Status__c</fullName>
    <label>Rsc1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc2_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc2_Callback_Date__c</fullName>
    <label>Rsc2 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc2_Comments__c.field-meta.xml
<CustomField>
    <fullName>Rsc2_Comments__c</fullName>
    <label>Rsc2 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc2_Status__c.field-meta.xml
<CustomField>
    <fullName>Rsc2_Status__c</fullName>
    <label>Rsc2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc3_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc3_Callback_Date__c</fullName>
    <label>Rsc3 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc3_Comments__c.field-meta.xml
<CustomField>
    <fullName>Rsc3_Comments__c</fullName>
    <label>Rsc3 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc3_Status__c.field-meta.xml
<CustomField>
    <fullName>Rsc3_Status__c</fullName>
    <label>Rsc3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc1_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc1_Callback_Date__c</fullName>
    <label>Sc1 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Sc1_Comments__c</fullName>
    <label>Sc1 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc1_Status__c.field-meta.xml
<CustomField>
    <fullName>Sc1_Status__c</fullName>
    <label>Sc1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc2_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc2_Callback_Date__c</fullName>
    <label>Sc2 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc2_Comments__c.field-meta.xml
<CustomField>
    <fullName>Sc2_Comments__c</fullName>
    <label>Sc2 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc2_Status__c.field-meta.xml
<CustomField>
    <fullName>Sc2_Status__c</fullName>
    <label>Sc2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc3_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc3_Callback_Date__c</fullName>
    <label>Sc3 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc3_Comments__c.field-meta.xml
<CustomField>
    <fullName>Sc3_Comments__c</fullName>
    <label>Sc3 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc3_Status__c.field-meta.xml
<CustomField>
    <fullName>Sc3_Status__c</fullName>
    <label>Sc3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FC In Progress</fullName>
                <default>true</default>
                <label>FC In Progress</label>
            </value>
            <value>
                <fullName>FC Pending</fullName>
            </value>
            <value>
                <fullName>SC Assigned</fullName>
            </value>
            <value>
                <fullName>SC In Progress</fullName>
            </value>
            <value>
                <fullName>SC Pending</fullName>
            </value>
            <value>
                <fullName>SC Reassigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/classes/SecondCallerNPADetailPageController.cls
public class SecondCallerNPADetailPageController {
    
    public class CustomerDetailsWrapper {
        public Net_Promoter_Score__c nps;
        public Boolean				 isNPA_AnalystLoggedIn;
        
        public CustomerDetailsWrapper() {
            nps = new Net_Promoter_Score__c();
            isNPA_AnalystLoggedIn = false;
        }
    }
    
      @AuraEnabled
    public static String getCustomerDetails(Id recordId) {
        CustomerDetailsWrapper data = new CustomerDetailsWrapper();
        data.nps 					= getNpaRecord(recordId);
        data.isNPA_AnalystLoggedIn	= SecondCallerNPAListController.validate_NPAAnalystLoggedIn();
        return JSON.serialize(data);
    }    
   
    public static Net_Promoter_Score__c getNpaRecord(Id recordId) {
        Net_Promoter_Score__c objNpa; 
        List<Net_Promoter_Score__c> lstNpa = [ Select Id
                                                    , Customer__c
                                                    , Customer__r.Customer_Name__c
                                                    ///Commented as per issue SB-269
                                                    //, Customer__r.Account_Name__c
                                                    , Customer__r.Contact_Mobile__c
                                                    , Customer__r.Contact_Email__c
                                                    , Customer__r.RecordTypeId
                                                    , NPA_Rating__c
                                                    , Fc1_Comments__c
                                                    , Fc2_Comments__c
                                                    , Fc3_Comments__c
                                                    , Sc1_Callback_Date__c
                                                    , Sc1_Comments__c
                                                    , Sc1_Status__c                                                   
                                                    , Sc2_Callback_Date__c
                                                    , Sc2_Comments__c
                                                    , Sc2_Status__c
                                                    , Sc3_Callback_Date__c
                                                    , Sc3_Comments__c
                                                    , Sc3_Status__c
                                                    , Rsc1_Callback_Date__c
                                                    , Rsc1_Comments__c
                                                    , Rsc1_Status__c
                                                    , Rsc2_Callback_Date__c
                                                    , Rsc2_Comments__c
                                                    , Rsc2_Status__c
                                                    , Rsc3_Callback_Date__c
                                                    , Rsc3_Comments__c
                                                    , Rsc3_Status__c
                                                    , Status__c
                                              		, Is_SC_Reassigned__c
                                              		, Reassign_Comments_1__c
                                              		, Reassign_Comments_2__c
                                              		, Reassign_Comments_3__c
                                              		, Reassign_Comments_4__c
                                              		, Reassign_Comments_5__c
                                                 From Net_Promoter_Score__c
                                                Where Id=:recordId];
        if(lstNpa != null && !lstNpa.isEmpty()){
                objNpa = lstNpa[0];
        }
        return objNpa;
    }
    
    @AuraEnabled
    public static Boolean closeNpaRecord(Id recordId) {
        Net_Promoter_Score__c objNpa = new Net_Promoter_Score__c(); 
        objNpa.Id = recordId;
        objNpa.Status__c = 'Closed';
        try{
            update objNpa;
            return true;
        }catch(Exception exp){
            System.debug('---->Exception'+exp);
            return false;
        }
        
    }
    
    
}