DHLQa2/force-app/main/default/objects/Customer__c/fields/Is_Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Key_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field signifies if the Customer is a Key Account or nit
If value is,
true - Customer is a key account
false - Customer is not a key account</description>
    <label>Is Key Account</label>
    <type>Checkbox</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Customer_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/NPA_Rating__c.field-meta.xml
<CustomField>
    <fullName>NPA_Rating__c</fullName>
    <label>NPA Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FC In Progress</fullName>
                <default>true</default>
                <label>FC In Progress</label>
            </value>
            <value>
                <fullName>FC Pending</fullName>
            </value>
            <value>
                <fullName>SC Assigned</fullName>
            </value>
            <value>
                <fullName>SC In Progress</fullName>
            </value>
            <value>
                <fullName>SC Pending</fullName>
            </value>
            <value>
                <fullName>SC Reassigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    public static List<Customer__c> createCustomers(String recordTypeName, Integer numCusts) {
        Schema.DescribeSObjectResult customerDesribe = Schema.SObjectType.Customer__c;
        Map<String,Schema.RecordTypeInfo> recTypeMapByName = customerDesribe.getRecordTypeInfosByDeveloperName();
        List<Customer__c> lstCust = new List<Customer__c>();
        
        for(Integer i=0; i < numCusts; i++) {
            Customer__c customer = new Customer__c();
            //Changed as per Issue SB-269 for NPA
            //customer.Account_Name__c ='TestAccount' + i;
            customer.Customer_Name__c ='Test Data ' + recordTypeName + ' ' +i;
            customer.recordTypeId = recTypeMapByName.get(recordTypeName).getRecordTypeId();
            lstCust.add(customer);
        }
        
        return lstCust;
    }

    public static Net_Promoter_Score__c createNps(String customerId, String status, String rating) {
        //List<Net_Promoter_Score__c> lstCust = new List<Net_Promoter_Score__c>();
        Net_Promoter_Score__c npa = new Net_Promoter_Score__c();
        npa.NPA_Rating__c = rating;
        npa.Customer__c = customerId;
        npa.Status__c = status;
        
        return npa;
    }
    
    public static List<User> createUsers(	String alias
                                          ,	String email
                                          ,	String lastName
                                          ,	Id profileId
                                          ,	String userName
                                          , Integer numberOfRecords
    ) {
        List<User> users = new List<User>();
        
        for (Integer i=0 ; i < numberOfRecords ; i++) {
            User usr = new User(
                  Alias 			= alias + ' ' + i
                , Email 			= email + '' + i
                , EmailEncodingKey  = 'UTF-8'
                , LastName			= lastName + ' ' + i
                , LanguageLocaleKey = 'en_US'
                , LocaleSidKey		='en_US'
                , TimeZoneSidKey	='America/Los_Angeles'
                , ProfileId 		= profileId
                , UserName			= userName + '' + i
            );
            users.add(usr);
         }
         
        
        insert users; 
        
        return users;
    }
    
    
     public static List<Customer__c> createCustomers(Id recordTypeId, Integer numCusts,Boolean isKeyAccount) {         

        List<Customer__c> lstCust = new List<Customer__c>();
        
        for(Integer i=0; i < numCusts; i++) {
            Customer__c customer = new Customer__c();
            customer.Customer_Name__c ='TestAccount' + i;
            customer.Is_Key_Account__c = isKeyAccount;
            customer.recordTypeId =recordTypeId;
            lstCust.add(customer);
        }
        
        return lstCust;
    }
    
    public static List<Customer__c> createCustomers(Id recordTypeId, Integer numCusts,Boolean isKeyAccount, String zone) {         

        List<Customer__c> lstCust = new List<Customer__c>();
        
        for(Integer i=0; i < numCusts; i++) {
            Customer__c customer 		= new Customer__c();
            customer.Customer_Name__c 	= 'TestAccount' + i;
            customer.Is_Key_Account__c 	= isKeyAccount;
            customer.recordTypeId 		= recordTypeId;
            customer.Region__c 			= zone;
            lstCust.add(customer);
        }
        
        return lstCust;
    }

    public static void createUserTouchpointConf(String touchpoints, String Username) {
         
        UserTouchpointConf__c userConfi = new UserTouchpointConf__c();
        userConfi.Name = Username;
        userConfi.Caller_Name__c = Username;
        userConfi.Touchpoints__c = touchpoints;
        
        Insert userConfi;
    }
    
    public static Map<String,Schema.RecordTypeInfo> getCustomerRecordTypeMap() {
         Schema.DescribeSObjectResult customerDesribe = Schema.SObjectType.Customer__c;
          return Schema.SObjectType.Customer__c.getRecordTypeInfosByName();
    }
    
     public static List<Customer__c> createCustomersTestData(String recordTypeName, Integer numCusts,Boolean isKeyAccount,String region) {
        Schema.DescribeSObjectResult customerDesribe = Schema.SObjectType.Customer__c;
        Map<String,Schema.RecordTypeInfo> recTypeMapByName = customerDesribe.getRecordTypeInfosByDeveloperName();
        List<Customer__c> lstCust = new List<Customer__c>();
        
        for(Integer i=0; i < numCusts; i++) {
            Customer__c customer = new Customer__c();
            //Changed as per Issue SB-269 for NPA
            //customer.Account_Name__c ='TestAccount' + i;
            customer.Customer_Name__c ='Test Data ' + recordTypeName + ' ' +i;
            customer.recordTypeId = recTypeMapByName.get(recordTypeName).getRecordTypeId();
            customer.Is_Key_Account__c = isKeyAccount;
            customer.Region__c = region;
            lstCust.add(customer);
        }
        
        return lstCust;
    }

}