DHLQa2/force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Customer__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

DHLQa2/force-app/main/default/objects/Customer__c/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Attempted_By__c</fullName>
    <label>Fc1 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Comments__c</fullName>
    <label>Fc1 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Attempted_By__c</fullName>
    <label>Fc2 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Comments__c</fullName>
    <label>Fc2 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Attempted_By__c</fullName>
    <label>Fc3 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Comments__c</fullName>
    <label>Fc3 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/classes/CaptureNpaDetailsControllerTest.cls
@isTest
public class CaptureNpaDetailsControllerTest {
    static testMethod void test_save() {
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers('Sales', 1);
        Insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'FC In Progress', '8');
        objNps.Fc1_Comments__c = 'Test comments1';
        objNps.Fc2_Comments__c = 'Test comments2';
        objNps.Fc3_Comments__c = 'Test comments3';
        Insert objNps;
        String parentId = lstsalesCust[0].Id;
       Test.startTest();
            String result = CaptureNpaDetailsController.save(objNps);
       Test.stopTest();
       Net_Promoter_Score__c resultNpa = [Select Id,Fc1_Attempted_By__c,Fc2_Attempted_By__c,Fc3_Attempted_By__c
                                         From Net_Promoter_Score__c 
                                         Where Id = :objNps.Id];
        System.assertNotEquals(null, resultNpa.Fc1_Attempted_By__c);
        System.assertNotEquals(null, resultNpa.Fc2_Attempted_By__c);
        System.assertNotEquals(null, resultNpa.Fc3_Attempted_By__c);
    }
    
    public static testMethod void test_Isdefaultmanager_Is_Not_LoggedIn() {
        
       Id billingRecordTypeId = Schema.SObjectType.Customer__c.getRecordTypeInfosByName().get('Billing').getRecordTypeId();         
      
        List<Profile> profiles = [
            SELECT Id 
            , Name
            FROM Profile
            WHERE Name Like 'Chief Service Officer(DHL)%'
            LIMIT 1
        ];
       
        List<User> users = TestDataFactory.createUsers(
                                    'standt'
                                   , 'user@testorg.com'
                                   , 'Testing'
                                   , ''+profiles[0].Id
                                   , 'user@testorg.com'
                                   , 1
                                  );
            
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers(billingRecordTypeId, 1, true, '');
        insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'Closed', '8');
        insert objNps;
        String parentId = lstsalesCust[0].Id;
        
        System.runAs(users[0]) {
            Test.startTest();
                    Net_Promoter_Score__c npa = CaptureNpaDetailsController.getNpa(parentId);
                    //System.assertEquals(null, CaptureNpaDetailsController.customerRegion, 'test_IsdefaultmanagerLoggedIn : Region is not as expected');
                    //String result = CaptureNpaDetailsController.checkIsDefaultManagerLoggedIn();
                    //System.assertEquals('false', result, 'test_Isdefaultmanager_Is_Not_LoggedIn : Default manager is not logged in');
            Test.stopTest();
        } 
               
    }
     public static testMethod void test_Isdefaultmanager_Is_LoggedIn() {
        
       Id billingRecordTypeId = Schema.SObjectType.Customer__c.getRecordTypeInfosByName().get('Billing').getRecordTypeId(); 
       String username ='tushar.kakade@eternussolutions.com.qa';
       List<User> users = [
           SELECT Id
             FROM User
            WHERE Username = :username
       ];
         
         if (users.isEmpty()) {
            List<Profile> profiles = [
                 SELECT Id 
                 , Name
                 FROM Profile
                 WHERE Name Like 'Chief Service Officer(DHL)%'
                 LIMIT 1
            ];
       
            users = TestDataFactory.createUsers(
                                        'standt'
                                       , username
                                       , 'Testing'
                                       , ''+profiles[0].Id
                                       , username
                                       , 1
                                      );
            users[0].username =   username;
            update users;
         }      
        
         
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers(billingRecordTypeId, 1, true, '');
        insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'Closed', '8');
        insert objNps;
        String parentId = lstsalesCust[0].Id;
        
        System.runAs(users[0]) {
            Test.startTest();
                    Net_Promoter_Score__c npa = CaptureNpaDetailsController.getNpa(parentId);
                    //System.assertEquals(null, CaptureNpaDetailsController.customerRegion, 'test_IsdefaultmanagerLoggedIn : Region is not as expected');
                    //String result = CaptureNpaDetailsController.checkIsDefaultManagerLoggedIn();
                    //System.assertEquals('true', result, 'test_Isdefaultmanager_Is_LoggedIn : Default manager is logged in');
            Test.stopTest();
        } 
               
    }
    
    public static testMethod void test_Isdefaultmanager_Region_Is_Not_Blank() {
      Id billingRecordTypeId = Schema.SObjectType.Customer__c.getRecordTypeInfosByName().get('Billing').getRecordTypeId(); 

       String username ='noor.rayini@dhl.com.st.qa';
       List<User> users = [
           SELECT Id
             FROM User
            WHERE Username = :username
       ];
         
         if (users.isEmpty()) {
            List<Profile> profiles = [
                 SELECT Id 
                 , Name
                 FROM Profile
                 WHERE Name Like 'Chief Service Officer(DHL)%'
                 LIMIT 1
            ];
       
            users = TestDataFactory.createUsers(
                                        'standt'
                                       , username
                                       , 'Testing'
                                       , ''+profiles[0].Id
                                       , username
                                       , 1
                                      );
            users[0].username =   username;
            update users;
         }      
        
         
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers(billingRecordTypeId, 1, true, '');
        lstsalesCust [0].Region__c = 'East';
        insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'Closed', '8');
        insert objNps;
        String parentId = lstsalesCust[0].Id;
        
        System.runAs(users[0]) {
            Test.startTest();
                    Net_Promoter_Score__c npa = CaptureNpaDetailsController.getNpa(parentId);
                    //System.assertEquals('East', CaptureNpaDetailsController.customerRegion, 'test_IsdefaultmanagerLoggedIn : Region is not as expected');
                    //String result = CaptureNpaDetailsController.checkIsDefaultManagerLoggedIn();
                    //System.assertEquals('false', result, 'test_Isdefaultmanager_Is_LoggedIn : Default manager is logged in');
            Test.stopTest();
        } 
    }
    
    public static testMethod void test_checkIsDefaultManagerLoggedIn() {
      Id billingRecordTypeId = Schema.SObjectType.Customer__c.getRecordTypeInfosByName().get('Billing').getRecordTypeId(); 

       String username ='noor.rayini@dhl.com.st.qa';
       List<User> users = [
           SELECT Id
             FROM User
            WHERE Username = :username
       ];
         
         if (users.isEmpty()) {
            List<Profile> profiles = [
                 SELECT Id 
                 , Name
                 FROM Profile
                 WHERE Name Like 'Chief Service Officer(DHL)%'
                 LIMIT 1
            ];
       
            users = TestDataFactory.createUsers(
                                        'standt'
                                       , username
                                       , 'Testing'
                                       , ''+profiles[0].Id
                                       , username
                                       , 1
                                      );
            users[0].username =   username;
            update users;
         }      
        
         
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers(billingRecordTypeId, 1, true, 'East');
        //lstsalesCust [0].Region__c = 'East';
        insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'Closed', '8');
        insert objNps;
        String parentId = lstsalesCust[0].Id;
        
        System.runAs(users[0]) {
            Test.startTest();
                    String value = CaptureNpaDetailsController.checkIsDefaultManagerLoggedIn(parentId);
                    //System.assertEquals('East', CaptureNpaDetailsController.customerRegion, 'test_IsdefaultmanagerLoggedIn : Region is not as expected');
                    //String result = CaptureNpaDetailsController.checkIsDefaultManagerLoggedIn();
                    //System.assertEquals('false', result, 'test_Isdefaultmanager_Is_LoggedIn : Default manager is logged in');
            Test.stopTest();
        } 
    }
}