DHLQa2/force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Attempted_By__c</fullName>
    <label>Fc1 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Attempted_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Attempted_Date__c</fullName>
    <label>Fc1 Attempted Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Callback_Date__c</fullName>
    <label>Fc1 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Comments__c</fullName>
    <label>Fc1 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc1_Status__c.field-meta.xml
<CustomField>
    <fullName>Fc1_Status__c</fullName>
    <label>Fc1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Attempted_By__c</fullName>
    <label>Fc2 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Attempted_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Attempted_Date__c</fullName>
    <label>Fc2 Attempted Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Callback_Date__c</fullName>
    <label>Fc2 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Comments__c</fullName>
    <label>Fc2 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc2_Status__c.field-meta.xml
<CustomField>
    <fullName>Fc2_Status__c</fullName>
    <label>Fc2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Attempted_By__c</fullName>
    <label>Fc3 Attempted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Attempted_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Attempted_Date__c</fullName>
    <label>Fc3 Attempted Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Callback_Date__c</fullName>
    <label>Fc3 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Comments__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Comments__c</fullName>
    <label>Fc3 Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Fc3_Status__c.field-meta.xml
<CustomField>
    <fullName>Fc3_Status__c</fullName>
    <label>Fc3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsucessful</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Asked to callback</fullName>
            </value>
            <value>
                <fullName>Incorrect number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Make_Second_Call__c.field-meta.xml
<CustomField>
    <fullName>Make_Second_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Make Second Call</label>
    <type>Checkbox</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/NPA_Rating__c.field-meta.xml
<CustomField>
    <fullName>NPA_Rating__c</fullName>
    <label>NPA Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FC In Progress</fullName>
                <default>true</default>
                <label>FC In Progress</label>
            </value>
            <value>
                <fullName>FC Pending</fullName>
            </value>
            <value>
                <fullName>SC Assigned</fullName>
            </value>
            <value>
                <fullName>SC In Progress</fullName>
            </value>
            <value>
                <fullName>SC Pending</fullName>
            </value>
            <value>
                <fullName>SC Reassigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/classes/CaptureNpaDetailsController.cls
public without sharing class CaptureNpaDetailsController {    
  
    public static String TRUE_VALUE      = 'true';
    public static String FALSE_VALUE     = 'false';    
    public static String DEFAULT_MANAGER = 'Default Manager';
    public static String ASKED_TO_CALLBACK = 'Asked to callback';

    
    @AuraEnabled
    public static String save(Net_Promoter_Score__c objNpa){
        Net_Promoter_Score__c existingNpaRec = getNpa(objNpa.Customer__c);
        
        if(objNpa.Fc1_Comments__c != null && objNpa.Fc1_Attempted_Date__c == null){
            objNpa.Fc1_Attempted_By__c = UserInfo.getName();
            objNpa.Fc1_Attempted_Date__c = System.now(); 
        }
        if(objNpa.Fc2_Comments__c != null && objNpa.Fc2_Attempted_Date__c == null) {
            objNpa.Fc2_Attempted_By__c = UserInfo.getName();
            objNpa.Fc2_Attempted_Date__c = System.now();
        }
        if(objNpa.Fc3_Comments__c != null && objNpa.Fc3_Attempted_Date__c == null) {
            objNpa.Fc3_Attempted_By__c = UserInfo.getName();
            objNpa.Fc3_Attempted_Date__c = System.now();
        }
        
        if(objNpa.Fc1_Attempted_By__c != null && objNpa.Fc1_Attempted_By__c != null 
           && objNpa.Fc1_Status__c == 'Successful' && String.IsEmpty(objNpa.NPA_Rating__c) 
           && !objNpa.Make_Second_Call__c){
            objNpa.NPA_Rating__c = '0';    
        }
        
        if(objNpa.Fc1_Status__c != null && (ASKED_TO_CALLBACK.equals(objNpa.Fc1_Status__c) == false) ){
            objNpa.Fc1_Callback_Date__c= null;    
        }
        
        if(objNpa.Fc2_Status__c != null && (ASKED_TO_CALLBACK.equals(objNpa.Fc2_Status__c) == false) ){
            objNpa.Fc2_Callback_Date__c= null;    
        }
        
        if(objNpa.Fc3_Status__c != null && (ASKED_TO_CALLBACK.equals(objNpa.Fc3_Status__c) == false) ){
            objNpa.Fc3_Callback_Date__c= null;    
        }
       
        try{
            if(existingNpaRec != null){
                   objNpa.Id = existingNpaRec.Id;
                   update objNpa;                	
            } else{
                   Insert objNpa;
                
             }            
             return 'success';
        }catch(Exception exp){            
             return 'error';
        }
                    
    }
    
    @AuraEnabled
    public static Net_Promoter_Score__c getNpa(Id parentId) {
      
        Net_Promoter_Score__c objNpa; 
        List<Customer__c> lstCustomer = [Select Id
                                              , Region__c
                                              , (Select Id
                                                      , Make_Second_Call__c
                                                      , NPA_Rating__c
                                                      , Fc1_Callback_Date__c
                                                      , Fc1_Comments__c
                                                      , Fc1_Status__c                                                     
                                                      , Fc2_Callback_Date__c
                                                      , Fc2_Comments__c
                                                      , Fc2_Status__c                                                    
                                                      , Fc3_Callback_Date__c
                                                      , Fc3_Comments__c
                                                      , Fc3_Status__c
                                                 	  , Status__c
                                                 From Net_Promoter_Scores__r
                                                Limit 1)
                                        From Customer__c
                                        Where Id=:parentId];       
        if(lstCustomer != null && !lstCustomer.isEmpty() && 
               lstCustomer[0].Net_Promoter_Scores__r.size() >0){                     
                   objNpa         = lstCustomer[0].Net_Promoter_Scores__r[0];
        }
        
        return objNpa;
    }
    
    @AuraEnabled
    public static String checkIsDefaultManagerLoggedIn(Id parentId) {       
        
         List<Customer__c> lstCustomer = [
             SELECT Id
             	  , Region__c
               FROM Customer__c
              WHERE Id = :parentId
        ];
        
        String customerRegion = '';
        if (!lstCustomer.isEmpty()) {
           customerRegion = lstCustomer[0].Region__c;          
        }
       
        if (String.isBlank(customerRegion)) {            
            Id loggedInuserId = Utils.getLoggedId();
            User usr = [
                SELECT Id
                     , username
                  FROM User
                 WHERE Id =: loggedInuserId
            ];       
            
            String loggedInUserName = usr.username;
            
            List<Touchpoint_Owner_mapping__mdt> metaData = [
                SELECT Username__c
                  FROM Touchpoint_Owner_mapping__mdt
                 WHERE Touchpoint_Name__c = :DEFAULT_MANAGER
            ];
            
            String username = metaData[0].Username__c;           
            if (username.equals(usr.username)) {               
                return TRUE_VALUE;
            } else {                 
                return FALSE_VALUE;
            }
        } else {
           return FALSE_VALUE;
        }
    }
}