DHLQa2/force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Customer__c/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FC In Progress</fullName>
                <default>true</default>
                <label>FC In Progress</label>
            </value>
            <value>
                <fullName>FC Pending</fullName>
            </value>
            <value>
                <fullName>SC Assigned</fullName>
            </value>
            <value>
                <fullName>SC In Progress</fullName>
            </value>
            <value>
                <fullName>SC Pending</fullName>
            </value>
            <value>
                <fullName>SC Reassigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/classes/SecondCallerNPADetailPageControllerTest.cls
@isTest
public class SecondCallerNPADetailPageControllerTest {
	static testMethod void test_getNpaRecord() {
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers('Sales', 10);
        lstsalesCust[0].Region__c = 'West';
        Insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'FC In Progress', '8');
        Insert objNps;
        String parentId = lstsalesCust[0].Id;
       Test.startTest();
            Net_Promoter_Score__c result = SecondCallerNPADetailPageController.getNpaRecord(objNps.Id);
       Test.stopTest();
       System.assertNotEquals(null, result);
    }
    
    static testMethod void test_closeNpaRecord() {
        List<Customer__c> lstsalesCust = TestDataFactory.createCustomers('Sales', 10);
        lstsalesCust[0].Region__c = 'West';
        Insert lstsalesCust;
        Net_Promoter_Score__c objNps = TestDataFactory.createNps(lstsalesCust[0].Id, 'FC In Progress', '8');
        objNps.Status__c = 'SC Reassigned';
        Insert objNps;
        
        String parentId = lstsalesCust[0].Id;
       Test.startTest();
            Boolean result = SecondCallerNPADetailPageController.closeNpaRecord(objNps.Id);
       Test.stopTest();
       System.assertEquals(true, result);
    }
}