DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Net Promoter Scores</relationshipLabel>
    <relationshipName>Net_Promoter_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Customer_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Days_since_SC_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Days_since_SC_Assignment__c</fullName>
    <formula>IF( ISBLANK(  SC_Assignment_Date__c  ) == FALSE 
 ,  TODAY() - SC_Assignment_Date__c
,0 )</formula>
    <label>Days since SC Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Is_SC_Reassigned__c.field-meta.xml
<CustomField>
    <fullName>Is_SC_Reassigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is SC Reassigned</label>
    <type>Checkbox</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Make_Second_Call__c.field-meta.xml
<CustomField>
    <fullName>Make_Second_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Make Second Call</label>
    <type>Checkbox</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/NPA_Rating__c.field-meta.xml
<CustomField>
    <fullName>NPA_Rating__c</fullName>
    <label>NPA Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc1_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc1_Callback_Date__c</fullName>
    <label>Rsc1 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc2_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc2_Callback_Date__c</fullName>
    <label>Rsc2 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Rsc3_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Rsc3_Callback_Date__c</fullName>
    <label>Rsc3 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc1_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc1_Callback_Date__c</fullName>
    <label>Sc1 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc2_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc2_Callback_Date__c</fullName>
    <label>Sc2 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Sc3_Callback_Date__c.field-meta.xml
<CustomField>
    <fullName>Sc3_Callback_Date__c</fullName>
    <label>Sc3 Callback Date</label>
    <type>DateTime</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/SC_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>SC_Assignment_Date__c</fullName>
    <description>The value in the fields describes the date when the net promoter score record was assigned to the touchpoint manager(2nd caller)</description>
    <inlineHelpText>The value in the fields describes the date when the net promoter score record was assigned to the touchpoint manager(2nd caller)</inlineHelpText>
    <label>SC Assignment Date</label>
    <type>Date</type>
</CustomField>

DHLQa2/force-app/main/default/objects/Net_Promoter_Score__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FC In Progress</fullName>
                <default>true</default>
                <label>FC In Progress</label>
            </value>
            <value>
                <fullName>FC Pending</fullName>
            </value>
            <value>
                <fullName>SC Assigned</fullName>
            </value>
            <value>
                <fullName>SC In Progress</fullName>
            </value>
            <value>
                <fullName>SC Pending</fullName>
            </value>
            <value>
                <fullName>SC Reassigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DHLQa2/force-app/main/default/classes/SecondCallerNPAListController.cls
public class SecondCallerNPAListController {
	
   public static Integer RATING_QUERY_FILTER 		= 9;
   public static String  CLOSED_STATUS 				= 'Closed';
   public static String  NPA_ANALYST_PROFILE_NAME	= 'Chief Service Officer(DHL)'; 
   public static String  FC_PENDING					= 'FC Pending';
   public static String  FC_IN_PROGRESS   		    = 'FC In Progress';

       
    public class NPADetailsWrapper {
        public String secondCallerName;
        public String npsTableName;
        
        public Boolean isNpaAnalystLoggedIn;
        
        public Integer targetCount;
        
        public List<Net_Promoter_Score__c> 		npsData;
        public List<String> 				  	npsTableColumnLabels;
        
        public NPADetailsWrapper () {
            secondCallerName 		= '';
            npsData 		 		= new List<Net_Promoter_Score__c>();
            npsTableColumnLabels 	= new List<String>();
            npsTableName			= '';
            targetCount				= 0;
            isNpaAnalystLoggedIn    = false;
        }
    }
    
     @AuraEnabled(cacheable=false)
    public static String getNPADetails() { 
        new NPADetailsWrapper();
        NPADetailsWrapper data 		= new NPADetailsWrapper();
        data.secondCallerName 		= Utils.getLoggedInUserName();
        data.isNpaAnalystLoggedIn   = validate_NPAAnalystLoggedIn();
        data.npsData		   		= getNPS_Data(data.isNpaAnalystLoggedIn);
        data.npsTableName 			= Label.DHL_Net_Promoter_Score_NPS_Table_Label;
        data.npsTableColumnLabels	= setNPSTableColumnLabels(data);
        data.targetCount			= getTargetTableCount(data.npsData); 
        return JSON.serialize(data);
    }
    
    public static Integer getTargetTableCount(List<Net_Promoter_Score__c> npsdata) {
        return [
            SELECT COUNT()
              FROM Net_Promoter_Score__c
             WHERE Status__c = :CLOSED_STATUS
               AND Id IN :npsdata
        ];
    }
    
    public static List<String> setNPSTableColumnLabels(NPADetailsWrapper data) {
        	data.npsTableColumnLabels = new List<String>();
            data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Customer_Name_Label);
            data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Status_Label);
            data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Rating_Label);
            data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Days_Since_Assigned_Label);
        	data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Next_Callback_Date_Label);
        	data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Is_Reassigned_Label);
        	data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_NPS_Table_Owner_Name_Label);
        	data.npsTableColumnLabels.add(Label.DHL_Net_Promoter_Score_Table_LastModifiedDate_Label);
        	data.npsTableColumnLabels.add(Label.DHL_Customer_Customer_Table_Touchpoint_Label);
            data.npsTableColumnLabels.add(Label.DHL_Customer_Customer_table_Customer_Id_Label);        
        return data.npsTableColumnLabels;
    }
    
   
    public static List<Net_Promoter_Score__c> getNPS_Data(Boolean isNpaAnalystLoggedIn) {
        List<Net_Promoter_Score__c> npsRecords = new List<Net_Promoter_Score__c>();
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
		
        for (Net_Promoter_Score__c nps :  [
            SELECT Id
            	 , Name
                 , Status__c
            	 , NPA_Rating__c
                 , Customer__r.Customer_Name__c
            	 , Days_since_SC_Assignment__c
            	 , Sc1_Callback_Date__c
            	 , Sc2_Callback_Date__c
            	 , Sc3_Callback_Date__c
            	 , Is_SC_Reassigned__c
            	 , Rsc3_Callback_Date__c
             	 , Rsc2_Callback_Date__c
            	 , Rsc1_Callback_Date__c
            	 , SC_Assignment_Date__c
            	 , Make_Second_Call__c
            	 , Customer__r.Name
            	 , Customer__r.Owner.Name
            	 , Customer__r.RecordType.Name
            	 , LastModifiedDate 
              FROM Net_Promoter_Score__c
             WHERE NPA_Rating__c != NULL
            ORDER BY CreatedDate DESC
            LIMIT 1000
        ]) {            
            
            if (   CLOSED_STATUS.equals(nps.Status__c)) {
                if (isNpaAnalystLoggedIn) {
                    npsRecords.add(nps);
                } else if (
                       !isNpaAnalystLoggedIn  
                	&& nps.SC_Assignment_Date__c != NULL
                    && nps.SC_Assignment_Date__c >= firstDayOfMonth
                    && nps.SC_Assignment_Date__c <= lastDayOfMonth 
                ) {
                    npsRecords.add(nps);
                }             
            }  else if (!CLOSED_STATUS.equals(nps.Status__c) ) {                   
                if ( 	!isNpaAnalystLoggedIn 
                    && 	Integer.valueOf(nps.NPA_Rating__c) < RATING_QUERY_FILTER
                    &&  nps.Make_Second_Call__c
                    &&  nps.Status__c != FC_PENDING
                    &&  nps.Status__c != FC_IN_PROGRESS
                   ) {                      
                       npsRecords.add(nps);
                   } else if (isNpaAnalystLoggedIn && !FC_IN_PROGRESS.equals(nps.Status__c )) {                      
                       npsRecords.add(nps);
                   }                  
            }
        }
                
        return npsRecords;
    }    
    
    public static Boolean validate_NPAAnalystLoggedIn() {
       Boolean isNpaAnalystLoggedIn = false;
        List<User> loggedInUser = [
            SELECT Id
            	 , profile.Name
              FROM User
             WHERE Id = :Utils.getLoggedId()
        ];
        
        if (!loggedInUser.isEmpty() && loggedInUser.size() == 1) {
            if (NPA_ANALYST_PROFILE_NAME.equals(loggedInUser[0].profile.Name)) {
               	isNpaAnalystLoggedIn = true;
            } else {
               	 isNpaAnalystLoggedIn = false;
            }
        } 
        System.debug('isNpaAnalystLoggedIn :'+isNpaAnalystLoggedIn);
        return isNpaAnalystLoggedIn;
    }
}